version: '3'
services:
  web:
    build: .
    command: >
      /bin/sh -c "python3 manage.py migrate --noinput &&
                  python3 manage.py collectstatic --noinput &&
                  uwsgi"
    volumes:
      - .:/code
  proxy:
    image: nginx:1.18-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www/static:ro
    depends_on:
      - web
    ports:
      - "80:80"
